[colors.bright]
black = "0x928374"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[colors.normal]
black = "0x282828"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[colors.primary]
background = "0x1d2021"
foreground = "0xebdbb2"

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.normal]
family = "Noto Sans Mono Medium"

[[keyboard.bindings]]
chars = "_"
key = "Space"
mods = "Shift"

[[schemes.github_dark.indexed_colors]]
color = "0xd18616"
index = 16

[[schemes.github_dark.indexed_colors]]
color = "0xf14c4c"
index = 17

[schemes.github_dark.bright]
black = "0x666666"
blue = "0x3b8eea"
cyan = "0x29b7da"
green = "0x23d18b"
magenta = "0xd670d6"
red = "0xf14c4c"
white = "0xd1d5da"
yellow = "0xf5f543"

[schemes.github_dark.normal]
black = "0x24292e"
blue = "0x3b8eea"
cyan = "0x29b7da"
green = "0x23d18b"
magenta = "0xbc3fbc"
red = "0xf14c4c"
white = "0xd1d5da"
yellow = "0xe2e210"

[schemes.github_dark.primary]
background = "0x24292e"
foreground = "0xd1d5da"

[[schemes.github_light.indexed_colors]]
color = "0xd18616"
index = 16

[[schemes.github_light.indexed_colors]]
color = "0xcd3131"
index = 17

[schemes.github_light.bright]
black = "0x666666"
blue = "0x0451a5"
cyan = "0x0598bc"
green = "0x14ce14"
magenta = "0xbc05bc"
red = "0xcd3131"
white = "0x586069"
yellow = "0xb5ba00"

[schemes.github_light.normal]
black = "0x697179"
blue = "0x0451a5"
cyan = "0x0598bc"
green = "0x14ce14"
magenta = "0xbc05bc"
red = "0xd03d3d"
white = "0x586069"
yellow = "0x949800"

[schemes.github_light.primary]
background = "0xffffff"
foreground = "0x586069"

[schemes.gruvbox_dark.bright]
black = "0x928374"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[schemes.gruvbox_dark.normal]
black = "0x282828"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[schemes.gruvbox_dark.primary]
background = "0x1d2021"
foreground = "0xebdbb2"

[schemes.gruvbox_light.bright]
black = "0x928374"
blue = "0x076678"
cyan = "0x427b58"
green = "0x79740e"
magenta = "0x8f3f71"
red = "0x9d0006"
white = "0x3c3836"
yellow = "0xb57614"

[schemes.gruvbox_light.normal]
black = "0xfbf1c7"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0x7c6f64"
yellow = "0xd79921"

[schemes.gruvbox_light.primary]
background = "0xf9f5d7"
foreground = "0x3c3836"

[window]
gtk_theme_variant = "dark"

[window.dimensions]
columns = 95
lines = 30

[window.padding]
x = 5
y = 5
