#! /bin/sh

polybar example &
nitrogen --restore &
nm-applet &
setxkbmap pl &
xfsettingsd &

# Chromium browsers tear when picom started immediately
bash -c "sleep 5; picom" &

wmname LG3D & # Fix java GUIs (intellij idea) not working with window managers
xsetroot -cursor_name left_ptr &

xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 1 &

bash -c "sleep 5; xset r rate 200 60 & setxkbmap -option 'caps:swapescape'" &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5
bspc config focused_border_color \#FF6666
bspc config marked_border_color \#66FF66

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config top_padding          0
bspc config bottom_padding       30
bspc config single_monocle       true

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
