#! /bin/sh

compton &
polybar example &
nitrogen --restore &
redshift &

setxkbmap -option "caps:swapescape" &
xset r rate 200 25 &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
